apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd
spec:
  generators:
  - list:
      elements:
      - cluster: test
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'bgd-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/c6h3un/openshift-gitops-workshop
        targetRevision: demo
        path: documentation/modules/ROOT/examples/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false